[env:esp32-c3]
platform  = espressif32
board     = esp32-c3-devkitm-1
framework = arduino

build_flags =
    -D FIRMWARE_VERSION='"1.0.0"'
    -D ARDUINO_USB_MODE=0           ; 关闭硬件 USB，IO18/IO19 还原为普通 UART
    -D ARDUINO_USB_CDC_ON_BOOT=0    ; 关闭 USB CDC，Serial 改走 UART0
    -D ARDUINO_DISABLE_JTAG=1

monitor_filters = esp32_exception_decoder

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0

board_build.flash_mode = dio
board_build.partitions = min_spiffs.csv

; esptool 通过 MC-121-L119（USB转UART桥）下载，与 USB CDC 无关，照常工作
upload_protocol = esptool
upload_port     = COM3
upload_speed    = 921600            ; 桥接芯片支持更高速率，可以加快下载
monitor_port    = COM3
monitor_speed   = 115200